# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: uwu.spec

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: test-repo
# downstream (Fedora) RPM package name
downstream_package_name: test-repo

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: uwu
    targets:
      - fedora-all
